on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/captcha

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dep
      run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

    - name: Install Dependencies and Run tests
      working-directory: src/captcha
      run: |
        dep ensure
        go test ./...